### ISSUE TITLE
Support templates without `Template:` prefix

### ISSUE THREAD

**Issue by emersonbroga** [spencermountain/wtf_wikipedia#27]
if you look at https://en.wikipedia.org/w/api.php?action=query&prop=revisions&rvprop=content&rvsection=0&format=json&pageids=23447 it starts with a {{multiple ... }}

and the parser is not detecting it.

In my code I used a regex to strip it out.
markup.replace(/{{multiple((.|\n)*?)}}/g, '');

But i didn't had time to take a look at your source and add it. Placing this issue here so you know about it.

(thanks for sharing, this saved my day).

**Comment by spencermountain** [comment]
ah, good one. Thanks Emerson, will take a look.

**Comment by emersonbroga** [comment]
The same goes for the tag {{Country}}

 https://en.wikipedia.org/w/api.php?action=query&prop=revisions&rvprop=content&rvsection=0&format=json&pageids=23442

Also those other ones that I found so far.
{{navbox ... }}
{{WikiProject ...}}
{{oldafdfull ...}}
{{WikiProjectBannerShell ...}}

**Comment by spencermountain** [comment]
hey, so since there are so many of these random ones, my policy has been to ignore/delete it unless it's a known template with a specific parsing strategy. This seems fine for stuff like BannerShell, but i'm a bit worried about that {{Country}} one, which has lots of good data. Isn't it supposed to be {{Infobox Country ..}} ? Do you know if it's the only one that works that way?
I'm happy to add this specific one, but i'm worried it may be part of a bigger problem?

**Comment by spencermountain** [comment]
hey Emerson, both of those links have no been fixed to `{{infobox country`- and so forth. there must be a bot that does this. 
Anybody know?

**Comment by spencermountain** [comment]
hey, i'm gonna close this, as both examples seem to have been fixed, at least in wikipedia ;)
cheers
