### ISSUE TITLE
Query in another language

### ISSUE THREAD

**Issue by manviny** [spencermountain/wtf_wikipedia#3]
Hello.

    Can I get the results in a different language?

    Great work, actually the best wikipedia parse written in js.

Best regards.

**Comment by spencermountain** [comment]
hi manviny, thanks for the kind words. this is a great idea.
the one issue is that different languages use different keywords, like 'Kategorie' instead of 'Category', and i've tried supporting (a bunch of languages)[https://github.com/spencermountain/wtf_wikipedia/blob/master/index.js#L11] in a spotty way, if its not working for your use case, I am happy to add more.

```javascript
wikipedia.from_api("Toronto", "de", function(markup){
  var text= wikipedia.plaintext(markup)
  //Toronto ist mit 2,6 Millionen Einwohnern..
})
````
cheers!
