### ISSUE TITLE
Support for geo templates and other Wikivoyage data

### ISSUE THREAD

**Issue by davelowndes** [spencermountain/wtf_wikipedia#322]
I've just used dumpster-dive on Wikivoyage EN dump at https://dumps.wikimedia.org/enwikivoyage/latest/enwikivoyage-latest-pages-meta-current.xml.bz2. 

I'm trying to pull out some key data from each page, e.g. for Shibuya in Tokyo:
```
{{geo|35.664036|139.698211}}
{{usabledistrict}}
{{IsPartOf|Tokyo}}
```

1. I am looking for the "geo" template in the Mongo documents but I'm not sure it's there (it's not near `{{usabledistrict}}` and `{{IsPartOf|Tokyo}}` data). Does this mean the template is not supported by wtf_wikipedia? If not, I'd like to contribute, it'd be nice to have a wiki page on adding support for new templates? Or can you suggest a simple template I can reverse engineer?
2. Is it possible to promote certain templates to the document root, currently `{{usabledistrict}}` and `{{IsPartOf|Tokyo}}` show as templates under the "Go next" section but ideally they'd be top level data items? Does everything need to be under a section?

Thanks heaps for wtf_wikipedia and dumpster-dive!

**Comment by spencermountain** [comment]
hey dave, great question.
i've added support for the wikivoyage `geo` template in `7.8.1`. You should be able to see it with a `npm i`.

you're right that wikivoyage templates may not be supported very well. I can't wait to look at cleaning this part of the code-base up, this winter.

Ya, the question about which templates are at document root is an annoying one, because all it takes is one page to have two `geo` templates, or something. You're free to design your json anyway you'd like, but you may have to do a few loops first.
cheers

**Comment by spencermountain** [comment]
(personal note: this conflicts with the {{geo}} flag of georgia.) 
enable it again when templates are split by wiki.
