### ISSUE TITLE
Template {{Title year}}

### ISSUE THREAD

**Issue by rabbitUdomly** [spencermountain/wtf_wikipedia#397]
How to convert template {{Title Year}} to text? 

Page title:
`Category:Military airbases established in 1952`

Text on wiki:
`This category is for military airbases established in the year 1952`

Text on edit page wiki:
`This category is for [[military airbase]]s established in the year '''[[{{Title year}}]]'''`

Text wtf_wikipedia:
`This category is for military airbases established in the year `

**Comment by wvanderp** [comment]
This will be difficult because wikipedia uses some lua to find the date in the current title.

we currently don't have an accurate way to get the title in most cases. 

so, when we have a title it could be easy to implement. but since we dont this is a hard one.

but if there is a solution we'll try it

**Comment by spencermountain** [comment]
hi @rabbitUdomly - whoa, i've never seen [Template:Title yea](https://en.wikipedia.org/wiki/Template:Title_year) - what a weird template.

yeah - like @wvanderp said, we only have the document title if you've got it from `.fetch()` or from dumpster-dive, or something like that. We could take a shot at it, using a regex, if `doc.title` exists - otherwise return `''`?
What do you think Wouter?

good find!

**Comment by wvanderp** [comment]
This sounds like an ok solution but keep in mind that we also try to guess the title in the document file. https://github.com/spencermountain/wtf_wikipedia/blob/91d0a733b529acf13ba0d83cf176452e69951fa9/src/01-document/Document.js#L32-L38
so the title might not be the title of the page and thus we might come to the wrong answer.

**Comment by spencermountain** [comment]
template added in 9.0.0
cheers
