### ISSUE TITLE
Infobox return incomplete for athletes

### ISSUE THREAD

**Issue by wif70068** [spencermountain/wtf_wikipedia#428]
Hi, first of all, I love your tool!

I noticed that for some athletes the infobox object doesn't deliver the medaltemplates attributes.

I tried Michael Phelps and Frank Stäbler. They use these templates: https://en.wikipedia.org/wiki/Template:Infobox_swimmer and https://en.wikipedia.org/wiki/Template:Infobox_sportsperson. Maybe this template also is relevant: https://en.wikipedia.org/wiki/Template:Infobox_medal_templates

Kind regards

**Comment by spencermountain** [comment]
hey @wif70068 apologies for the delay, i've been really busy this week.
You're right - we should support the MedalCount template. You can see some of the data by calling `doc.templates('MedalCount')` but we should parse it [properly](https://en.wikipedia.org/wiki/Template:MedalCount).

If you wanted to get a head-start on it, you can add a custom template parser, [as described here](https://github.com/spencermountain/wtf_wikipedia#adding-new-templates). Otherwise, i'm happy to add this in the next release.
cheers

**Comment by spencermountain** [comment]
{{medalcount}} template is now supported in 10.1.0
 thanks!
