### ISSUE TITLE
TypeError: callback is not a function

### ISSUE THREAD

**Issue by Vacilando** [spencermountain/wtf_wikipedia#452]
TypeError: callback is not a function at /mysitepath/node_modules/wtf_wikipedia/builds/wtf_wikipedia.js:9644:9

When I debug like this:
```
if (callback) {
  console.log(url)
  console.log(typeof(data))
  console.log(data)
  callback(null, data);
}
```
I get this:
- https://en.wikipedia.org/w/api.php?action=query&prop=revisions%7Cpageprops&rvprop=content&maxlag=5&rvslots=main&origin=*&format=json&redirects=true&titles=Future
- object
- Document$2 {}

It looks to me that `data` should be a function but it's `object`.

Versions installed:
- wtf_wikipedia 9.0.3
- wtf-plugin-summary 0.3.2
- wtf-plugin-image 0.3.2
- wtf-plugin-html 0.2.4

Things work when I downgrade to:
- wtf_wikipedia 8.5.1

**Comment by spencermountain** [comment]
hey @Vacilando i'll need instructions to reproduce this,
I know the fetch method has changed in v9
thanks

**Comment by wvanderp** [comment]
Hello @Vacilando,

I think there is a misunderstanding about how a callback works.

I like to program with promises/async-await. Before that, we used callbacks.
these are all solutions for the problem that it takes a while to do the API call

a promise uses the then syntax:

```
wtf.fetch('computer').then((data) => document.append(data.text())
```

or the await syntax

```
let data = await wtf.fetch('computer)
document.append(data.text())
```

The callback works a bit different. You provide fetch with a function that will be called when the API call is done.
like this:

```
let callbackfn = (error, data) => document.append(data.text())
wtf.fetch('computer', {}, callback)
```

When the fetch is done, it will call the callback function with any error if there was one and the data.

So I think that the function is implemented correctly but that it is used wrong.

In your `gatsby-wikipedia-fetcher` plugin, I see that you use the promise syntax, so there is no need for a callback.

I also want to alert you to a breaking change in the fetch function: 
the third parameter always gets interpreted as the callback now.

you use the old syntax on this line https://github.com/Vacilando/gatsby-wikipedia-fetcher/blob/e493ee0075c223c8296108682f252d062fa644a2/gatsby-node.js#L143

the old syntax was fetch(pagename, language, options or callback) or fetch(pagename, callback)
this is now changed to fetch(pagename, options, callback)
the language setting is now integrated into the options object under the `lang` key

I hope this answer can help you fix this problem.

p.s. the example will not work because you can append text to the DOM Document, but it is a nice illustration

**Comment by Vacilando** [comment]
Thanks @wvanderp for the clear explanation of the problem and the helpful clarification of the differences between promises and callbacks.

Basically the problem was that I used the old syntax for the fetch function. That is now fixed and the new version of https://github.com/Vacilando/gatsby-wikipedia-fetcher works fine with wtf_wikipedia v9!
